### ISSUE TITLE
[Improvements] Source Code

### ISSUE THREAD

**Issue by samuelscheit** [SpoticordMusic/SpoticordBot-v1#2]
In line [``100`` of ``core.ts``](https://github.com/SpoticordMusic/Spoticord/blob/main/src/command/core.ts#L100) you are initializing regex every time you call the function which is very expensive.
Instead you should create constants at the top of file.

**Comment by DaXcess** [comment]
Fixed in 6020f3d48a35e5ac82c6d94931360bc7bf519c65
