### ISSUE TITLE
[Improvements] play real Spotify songs instead of YouTube

### ISSUE THREAD

**Issue by samuelscheit** [SpoticordMusic/SpoticordBot-v1#3]
Instead of searching and playing YouTube songs with the same name, that sometimes have annoying intros you could play the real spotify song.
There are multiple libs out there for other languages:
- [librespot rust](https://github.com/librespot-org/librespot)
- [librespot go](https://github.com/librespot-org/librespot-golang)
- [librespot java](https://github.com/librespot-org/librespot-java)

Sadly they only work with Username + Password but they work with OAuth token under the hood so it might be possible to use them as a playback device and potentially maybe increase performance

**Comment by DaXcess** [comment]
There is a good chance that this may break Spotify ToS. I am not planning on adding this anytime soon, but I may ask Spotify directly about this sometime in the future.
