### ISSUE TITLE
[ENHANCEMENT] Volume boost

### ISSUE THREAD

**Issue by iamjonmiller** [SpoticordMusic/SpoticordBot-v1#6]
Was thinking about a different way to have a friendly spotify bot and realized there had to be a solution that just leveraged Spotify "devices", found this and had it working in a few minutes. Then I noticed that the volume was painfully low. At 200% volume in discord it just wasn't anywhere close to native spotify. I suspect this might have something to do with the volume boost you can select within Spotify clients. No biggie, but would be something to dig into,

**Comment by DaXcess** [comment]
What was your volume at the time of playback?
Spoticord also uses the volume in your Spotify client to control it's volume.

**Comment by DaXcess** [comment]
Closing after 7 days of inactivity
